FROM cecton/nginx-with-substitution-filter
#ADD default.conf /etc/nginx/conf.d/ 
#COPY nginx.conf /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf

